name: Deploy StoryBook to GitHub Pages

on:
  push:
    branches:
      - 'master'

jobs:
  setup:
    name: Setup deployment environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

  deploy-production:
    name: Deploy StoryBook
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v1
      - name: Deploying on GitHub Pages
        run: yarn run deploy-storybook --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
